name: Sync Airtable to Supabase

on:
  # Запуск по расписанию - каждые 72 часа
  schedule:
    - cron: '0 */72 * * *'  # Каждые 72 часа
  
  # Возможность запустить вручную через GitHub UI
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Шаг 2: Установить Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Шаг 3: Установить зависимости
      - name: Install dependencies
        run: npm ci
      
      # Шаг 4: Запустить ETL pipeline
      - name: Run sync script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scripts/sync-airtable.js
      
      # Шаг 5: Логирование результата
      - name: Log success
        if: success()
        run: |
          echo "✅ Sync completed successfully at $(date)"
          echo "Check Supabase dashboard for new records"
      
      - name: Log failure
        if: failure()
        run: |
          echo "❌ Sync failed at $(date)"
          echo "Check the logs above for error details"